ajdbc:
  datasource:
    driver-class-name: com.zaxxer.hikari.HikariDataSource
    username: devuser
    password: devpassword
    url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=dbhost)(PORT=1542))(CONNECT_DATA=(SERVER=dedicated)(SERVICE_NAME=DB_SERVICE)))